package game.square.action;

public enum ActionSquareType {
	CHANCE, COMMUNITY_CHEST, ROLL_THREE, GO, BONUS, PAY_DAY, INCOME_TAX, LUXURY_TAX, TAX_REFUND, SUBWAY, HOLLAND_TUNNEL,
	BIRTHDAY_GIFT

}